# Generated by Django 3.2.10 on 2022-01-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20220103_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
